NO = 1
while NO <=5:
    print(NO*2)
    NO += 1


    # EX:02
button = 1
print(button * 3)
button = button + 1
print(button * 3)
button = button + 1


# EX: 02

n = 0
i = 1
while n <= 5:
    n = n + 15
    i = i * 25
    print(n, i)
    if(n == 5 and i == 5):
     print(n + 40)

# EX: 03

max_value = int(input("Enter the maximum value: "))
fc = 1
n = 1
while n <= max_value:
    fc = fc * n
    n += 1


# ex 04

num = int(input("Enter a number: "))
print(num * 2)